# Generated by Django 4.2.3 on 2023-07-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Содержимое статьи')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров')),
                ('published_on', models.BooleanField(default=False, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'permissions': [('set_published_blog', 'Can publish blog')],
            },
        ),
    ]
